numpy array is collection of homogenous data

In [1]:
import numpy as np
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

Basic properties of array

In [4]:
type(x)

numpy.ndarray

In [5]:
x.shape 

(4,)

In [6]:
x.ndim #dimension of the array

1

In [8]:
x.dtype #datatype of the elements with array

dtype('int32')

In [9]:
#This is an example for creating a 5x4 array

Creating a 2d array

In [11]:
x=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [12]:
#this same array can be created using shortmodules

In [2]:
# this will create an array of 5x4 size with range of 0-19
x=np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
# will create an array of 20 elements with random numbers between 10 - 20
x=np.random.randint(10,high=20,size=(5,4))
x

array([[16, 13, 19, 17],
       [19, 17, 10, 12],
       [18, 12, 13, 17],
       [10, 16, 19, 12],
       [14, 18, 16, 14]])

In [4]:
#creating a 2x2x4 array from 2 arrays
x=np.arange(8).reshape(2,4)
y=np.arange(8,16).reshape(2,4)


In [5]:
z=np.stack((x,y))   #stack is used to join two similar arrays on z axis
z

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [24]:
z.shape

(2, 2, 4)

In [6]:
#creating a 5x4 array different method

In [7]:
x = np.random.randint(20,size=(5,4))
x

array([[ 0, 14, 18,  0],
       [14, 18, 13, 18],
       [ 5,  8, 13,  7],
       [ 8, 16,  0,  4],
       [ 4,  4, 13,  5]])

In [8]:
#creatin an array with 3x2x5

In [9]:
x = np.random.randint(30,size=(3,2,5))
x

array([[[15, 12, 12, 15, 18],
        [12, 21, 21, 20, 22]],

       [[29,  7,  1,  5, 10],
        [23, 16, 26, 24, 16]],

       [[ 0,  6, 12, 18, 13],
        [ 0, 17, 26, 10, 14]]])

In [10]:
# stacking of 3 arrays
x = np.arange(10).reshape(2,5)
y = np.arange(10,20).reshape(2,5)
w = np.arange(20,30).reshape(2,5)

In [11]:
z = np.stack((x,y,w))

In [12]:
z
z.shape

(3, 2, 5)

In [50]:
b=np.array_split(z,3)
b

[array([[[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]]),
 array([[[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]]),
 array([[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]])]

### Zero array
creating an array of zeros

In [2]:
import numpy as np
x=np.zeros((3,4,5))
print(x)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### zero array of 2x3

In [3]:
x=np.zeros((2,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]]


# change data type of array

### Creating array of ones

In [13]:
x=np.ones((2,3,3),dtype=int)
print(x)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [14]:
# matrix multiplication
x=np.ones((2,3,3),dtype=int)*3
print(x)

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


### create an array of evenly placed

In [15]:
import numpy as np
x=np.arange(2,50,5)    #arange instead of range a-array range
x


array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

### Line space

In [16]:
#used to split
# used to create bins
x=np.linspace(1,100,10)   #it splits 1,100 in 10 splits with same difference
print(x)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [17]:
x=np.linspace(0,100)    #the default sep value is 50 ie the fuction splits the arange into 50 parts as default if not provided with step value
print(x)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [11]:
x=np.linspace(1,101)
print(x)

[  1.           3.04081633   5.08163265   7.12244898   9.16326531
  11.20408163  13.24489796  15.28571429  17.32653061  19.36734694
  21.40816327  23.44897959  25.48979592  27.53061224  29.57142857
  31.6122449   33.65306122  35.69387755  37.73469388  39.7755102
  41.81632653  43.85714286  45.89795918  47.93877551  49.97959184
  52.02040816  54.06122449  56.10204082  58.14285714  60.18367347
  62.2244898   64.26530612  66.30612245  68.34693878  70.3877551
  72.42857143  74.46938776  76.51020408  78.55102041  80.59183673
  82.63265306  84.67346939  86.71428571  88.75510204  90.79591837
  92.83673469  94.87755102  96.91836735  98.95918367 101.        ]


# creating an array of constants

In [18]:
import numpy as np
x = np.full((2,3),6)   #in this way we can create a matrix of 6
x

array([[6, 6, 6],
       [6, 6, 6]])

## creating a matrix array by taking input from user

In [19]:
a = int(input("enter the number: "))
x = np.full((2,3),a)
x

array([[2, 2, 2],
       [2, 2, 2]])

# create an identity matrix

In [20]:
x = np.eye(5,5)  #eye is used to create identity matrix
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
#to change dtype
x = np.eye(2,2,dtype=int)
x

array([[1, 0],
       [0, 1]])

# introduction to random library in python

In [22]:
x = np.random.random((2,2,3))
x    # this will create a matrix/array whose values ly between 0 and 1

array([[[0.32506883, 0.4767059 , 0.76340124],
        [0.16016178, 0.33796403, 0.95364867]],

       [[0.43185627, 0.63822536, 0.11090792],
        [0.90249047, 0.4743616 , 0.35216892]]])

### example of random  module

##### rand range  #will display any one element between the specified range

In [ ]:
import random as re

In [ ]:
x = re.randrange(1,50)  #displays elements randomly within the range
x

33

In [ ]:
x = re.randint(1,50)
x

36

<div class="mark">
<span class="mark">rand int</span> will <span class="mark">display</span> a <span class="mark">random integer</span> between the specified range</div><i class="fa fa-lightbulb-o "></i>

### choice

<span class="mark">random.choice</span>(tuple)

In [ ]:
tup = ("we","are",1,2,3,"here")
re.choice(tup)  #choice is mostly used inside a tuple


'here'

### shuffle
used to shuffle the list/tupple

In [ ]:
import random as re
lst=[1,2,3,4,5,6,7,8,"hello"]
b=re.shuffle(lst)
print(b)

None


### sample

In [ ]:
lst=[1,2,3,4,5,6,7,8,"hello"]
x = re.sample(lst,3)

In [ ]:
x  # prints the random 3 vars from the list

[4, 2, 'hello']