# creating an random array with random lib

<span class="mark">x = np.random.randint(10,size=8)</span>

In [ ]:
#imp
x = np.random.randint(10,size=8)
x

array([2, 3, 0, 7, 3, 3, 0, 2])

this will create a one dimension array wth size 8, we can modify the array with reshape

 reshape

<span class="mark">converting a one dimension array to 2d/3d with the equal elements</span>

In [ ]:
b=x.reshape(2,4)
b

In [ ]:
##### cretaing 2d aray with random lib

In [ ]:
x = np.random.randint(10,size=(2,4))
x

array([[3, 0, 2, 5],
       [7, 7, 9, 9]])

In [ ]:
#### creating a 3d array with random

In [ ]:
x = np.random.randint(10,size=(2,3,4))
x

array([[[3, 5, 6, 3],
        [5, 8, 8, 5],
        [4, 0, 6, 4]],

       [[3, 8, 2, 0],
        [5, 9, 0, 5],
        [7, 9, 7, 0]]])

In [ ]:
#creating a complex data type 3d array

In [ ]:
x = np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]],dtype=complex)

In [ ]:
# x=np.random.randint(12,size=(3,2,2))
# complex(x)
# #dont know the method t convert to complex

In [ ]:
x

array([[[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
        [1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j]],

       [[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
        [1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j]]])

In [ ]:
# creating a 2x2 array of x and y

In [17]:
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

x [[1 2]
 [2 5]]
----------
y [[3 7]
 [7 5]]


In [ ]:
#we can also create a 2x2 arra with this random method

In [7]:
a = np.random.randint(4,size=(2,2))
b = np.random.randint(4,size=(2,2))


In [15]:
print('a',a)
print('------------')
print('b',b)

a [[0 0]
 [3 3]]
------------
b [[1 0]
 [3 3]]


# Addition of two or more arrays

c = <span class="mark">np.add</span>(x,y)

In [18]:
import numpy as np
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

x [[1 2]
 [2 5]]
----------
y [[3 7]
 [7 5]]


In [20]:
c = np.add(x,y)
c

array([[ 4,  9],
       [ 9, 10]])

# division of 2 arrays

b = <span class="mark">np.divide</span>(x,y)

In [21]:
import numpy as np
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

x [[1 2]
 [2 5]]
----------
y [[3 7]
 [7 5]]


In [22]:
np.divide(x,y)

array([[0.33333333, 0.28571429],
       [0.28571429, 1.        ]])

# multiplication

In [ ]:
import numpy as np
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

In [ ]:
np.multiply(x,y)

array([[ 3, 14],
       [14, 25]])

# subtraction of two arrays

In [ ]:
import numpy as np
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

In [ ]:
np.subtract(x,y)

array([[-2, -5],
       [-5,  0]])

# square of an array

In [ ]:
import numpy as np
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

In [ ]:
np.square(x)

array([[ 1,  4],
       [ 4, 25]], dtype=int32)

In [ ]:
np.square(y)

array([[ 9, 49],
       [49, 25]], dtype=int32)

# array raised to power n

In [ ]:
import numpy as np
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

In [ ]:
np.power(x,3)

array([[  1,   8],
       [  8, 125]], dtype=int32)

In [ ]:
np.power(y,4)

array([[  81, 2401],
       [2401,  625]], dtype=int32)

# square root of an array

In [ ]:
import numpy as np
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

In [ ]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.41421356, 2.23606798]])

# resiprocal of an array

<span class="mark">we first must convert the datatype to float</span>

In [ ]:
import numpy as np
x=np.array([[1,2],[2,5]])
y=np.array([[3,7],[7,5]])
print('x',x)
print(10*'-')
print('y',y)

In [ ]:
np.reciprocal(x) #this will only display 1 and zero, so we have to change the datatype of x to float

array([[1, 0],
       [0, 0]], dtype=int32)

In [ ]:
x=np.array([[1,2],[3,4]],dtype=float)
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
np.reciprocal(x)

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ]])

# sin #cos # tan

In [ ]:
#creating a random 2x2 2d array

In [ ]:
x=np.array([[1,2],[3,4]])


In [ ]:
#creating a random 3x2x5 array

In [ ]:
y=np.random.randint(30,size=(3,2,5))

In [ ]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [ ]:
np.sin(y)

array([[[ 0.91294525,  0.76255845,  0.65028784,  0.90929743,
         -0.53657292],
        [ 0.65028784, -0.95892427, -0.95892427,  0.84147098,
          0.99060736]],

       [[-0.8462204 , -0.7568025 , -0.95892427, -0.28790332,
         -0.90557836],
        [ 0.14112001,  0.14987721, -0.54402111,  0.98935825,
         -0.28790332]],

       [[ 0.6569866 ,  0.84147098, -0.66363388, -0.2794155 ,
         -0.54402111],
        [ 0.91294525, -0.7568025 ,  0.98935825,  0.84147098,
         -0.99999021]]])

In [ ]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [ ]:
np.cos(y)

array([[[ 0.40808206,  0.64691932, -0.75968791, -0.41614684,
          0.84385396],
        [-0.75968791,  0.28366219,  0.28366219,  0.54030231,
          0.13673722]],

       [[-0.53283302, -0.65364362,  0.28366219, -0.95765948,
          0.42417901],
        [-0.9899925 ,  0.98870462, -0.83907153, -0.14550003,
         -0.95765948]],

       [[ 0.75390225,  0.54030231, -0.74805753,  0.96017029,
         -0.83907153],
        [ 0.40808206, -0.65364362, -0.14550003,  0.54030231,
          0.0044257 ]]])

In [ ]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [ ]:
np.tan(y)

array([[[ 2.23716094e+00,  1.17875355e+00, -8.55993401e-01,
         -2.18503986e+00, -6.35859929e-01],
        [-8.55993401e-01, -3.38051501e+00, -3.38051501e+00,
          1.55740772e+00,  7.24460662e+00]],

       [[ 1.58815308e+00,  1.15782128e+00, -3.38051501e+00,
          3.00632242e-01, -2.13489670e+00],
        [-1.42546543e-01,  1.51589471e-01,  6.48360827e-01,
         -6.79971146e+00,  3.00632242e-01]],

       [[ 8.71447983e-01,  1.55740772e+00,  8.87142844e-01,
         -2.91006191e-01,  6.48360827e-01],
        [ 2.23716094e+00,  1.15782128e+00, -6.79971146e+00,
          1.55740772e+00, -2.25950846e+02]]])

<span class="mark">#np.cot(x)  #cot,#cosec</span> function does not exist in numpy, so we take the <span class="mark">reciprocal</span> of <span class="mark">sin,cos,tan</span> to obtain their values

# floor division of arrays


#floor division rounds the value to the nearest lower integer

In [23]:
#creating a 4x4 2d array

In [ ]:
x=np.array([[1.2,.5,2.6,7.9],[1.7,4.8,3.6,9.3],[1.6,2.5,3.8,9.6],[3.6,2.5,7.4,4.6]])
x

array([[1.2, 0.5, 2.6, 7.9],
       [1.7, 4.8, 3.6, 9.3],
       [1.6, 2.5, 3.8, 9.6],
       [3.6, 2.5, 7.4, 4.6]])

In [ ]:
np.floor(x)

array([[1., 0., 2., 7.],
       [1., 4., 3., 9.],
       [1., 2., 3., 9.],
       [3., 2., 7., 4.]])

# ceil division
#ceil will round the array to the nearest highest value

In [ ]:
np.ceil(x)

array([[ 2.,  1.,  3.,  8.],
       [ 2.,  5.,  4., 10.],
       [ 2.,  3.,  4., 10.],
       [ 4.,  3.,  8.,  5.]])

# round

#if values less the.5 will give lower int else will give higher int

In [ ]:
np.round(x)

array([[ 1.,  0.,  3.,  8.],
       [ 2.,  5.,  4.,  9.],
       [ 2.,  2.,  4., 10.],
       [ 4.,  2.,  7.,  5.]])

In [ ]:
import numpy as np

In [24]:
x = np.random.randint(8,size=8) #creating a one dimension array with length 8
y = np.random.randint(10,size=(2,5)) #creating a 2 dimension array
z=np.random.randint(12,size=(2,3,2)) #creating a 3d array
print('x',x)
print(10*'--')
print('y',y)
print(10*'--')
print('z',z)

x [6 7 4 0 6 7 2 2]
--------------------
y [[7 6 9 6 9]
 [7 6 9 3 9]]
--------------------
z [[[ 6  6]
  [ 7  8]
  [ 9 11]]

 [[ 3 11]
  [ 3  0]
  [10  0]]]


In [32]:
print('x.shape:',x.shape)    #finding the shape of array
print('x.ndim:',x.ndim)      #dimension of an array
print('x.dtype:',x.dtype)#datatype of the array
print(10*'--')
print('y.shape:',y.shape)
print('y.ndim:',y.ndim)
print('y.dtype:',y.dtype)
print(10*'--')
print('z.shape:',z.shape)
print('z.ndim:',z.ndim)
print('z.dtype:',z.dtype)

x.shape: (8,)
x.ndim: 1
x.dtype: int32
--------------------
y.shape: (2, 5)
y.ndim: 2
y.dtype: int32
--------------------
z.shape: (2, 3, 2)
z.ndim: 3
z.dtype: int32


# astype:

#used to <span class="mark">convert/change datatype</span> of an array

c=b<span class="mark">.astype(complex)</span>
c

In [ ]:
# creating a 5x2 2d array

In [ ]:
b = np.arange(1,11).reshape(5,2)
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#coverting the create array to complex type

In [ ]:
c=b.astype(complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j],
       [ 5.+0.j,  6.+0.j],
       [ 7.+0.j,  8.+0.j],
       [ 9.+0.j, 10.+0.j]])

In [ ]:
a = x.astype(complex) #cnversionelements inside array of int to complex

In [ ]:
a

array([1.+0.j, 6.+0.j, 4.+0.j, 7.+0.j, 7.+0.j, 5.+0.j, 3.+0.j, 5.+0.j])

In [ ]:
b = y.astype(float)
b

array([[0., 4., 5., 1., 4.],
       [0., 2., 9., 3., 8.]])

In [ ]:
c = z.astype(str)

In [ ]:
c

array([[['4', '3'],
        ['2', '7'],
        ['5', '8']],

       [['1', '2'],
        ['4', '1'],
        ['4', '3']]], dtype='<U11')

In [ ]:
a.dtype

dtype('complex128')

# array indexing

In [34]:
x = np.arange(1,11).reshape(10)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
print(x[3]) #we pick out the element at the third index position
print(x[-1])

4
10


In [ ]:
#creating an random matrix of 2x3 order

In [37]:
y = np.random.randint(10,size=(2,3)) 
y

array([[6, 9, 3],
       [6, 4, 1]])

In [ ]:
#array_name[second_row,second_element]

In [ ]:
y[1,1]  

2

In [ ]:
# creating a 3x2x3 array

In [38]:
y = np.random.randint(10,size=(3,2,3))
y

array([[[3, 7, 4],
        [9, 4, 2]],

       [[6, 5, 1],
        [9, 1, 1]],

       [[3, 7, 6],
        [2, 7, 1]]])

In [ ]:
#array_mname[third_layer,first_row,Third_element]

In [39]:
y[2,0,2]

6

In [40]:
# creating a 4x3 array

In [ ]:
x = np.random.randint(10,size=(4,3))
x

array([[6, 8, 8],
       [5, 0, 1],
       [6, 2, 2],
       [5, 5, 1]])

In [ ]:
#array_name[Third_row,third_element]

In [ ]:
x[2,2] #nums written inside are index numbers

2

In [ ]:
#arrayname[Third_row,second element]

In [ ]:
x[2,1]

2

In [ ]:
#arrayname[fourth_row,last_element]

In [ ]:
x[3,-1]

1

In [ ]:
#displaying third row completely
#array_name[indexnum_Thirdrow]

In [ ]:
x[2]

array([5, 5, 6])

# slicing

 [1:10] in this or any slicing operation the 10th index position is not included
The list will slice from 0,1,2,3,4,5,6,7,8,9

In [ ]:
#creating a one dimension array

In [41]:
x = np.random.randint(10,size=7)
x

array([0, 9, 1, 6, 8, 2, 6])

In [42]:
#arrayname[Third_element,last_element]
x[2:-1]   #last index will not be selected

array([1, 6, 8, 2])

In [43]:
#array[fourth_element:last_element]
x[3:]

array([6, 8, 2, 6])

In [44]:
#array[first_element:fifth_element]
x[:5]

array([0, 9, 1, 6, 8])

In [45]:
#used to display complete array
a[:]


array([[0, 0],
       [3, 3]])

In [46]:
#creating a random array of 4x3
y = np.random.randint(10,size=(4,3))
y

array([[8, 2, 2],
       [3, 3, 7],
       [3, 8, 9],
       [3, 8, 0]])

In [ ]:
y[2:]

array([[1, 9, 5],
       [0, 9, 4]])

In [47]:
#array[secondrow:lastrow,second_column:last_column]
#here we sliced the rows first and then sliced the columns
y[2:,1:]

array([[8, 9],
       [8, 0]])

In [48]:
#array[Third_row:last_row,first_column_element:second_column_element]
y[2:,0:2]

array([[3, 8],
       [3, 8]])

In [ ]:
#array[full_array,second_column]
y[:,1]

In [ ]:
#array[3rd_row]
y[2]

# slicing and indexing

In [50]:
#creating a 3 dimension matrix
x = np.random.randint(10,size=(2,3,3))
x

array([[[3, 8, 8],
        [9, 6, 7],
        [1, 6, 3]],

       [[8, 4, 9],
        [4, 0, 0],
        [3, 2, 5]]])

In [51]:
#array[second_layer,second_row,thrd_element]
x[1,1,2]

0

In [ ]:
#array[first_layer,second_row,first_element]
x[0,1,1]

In [52]:
# creating a random array 3x3x3
import numpy as np
x = np.random.randint(10,size=(3,3,3))
x

array([[[1, 0, 3],
        [8, 6, 4],
        [8, 4, 8]],

       [[0, 9, 0],
        [3, 2, 8],
        [4, 1, 7]],

       [[8, 4, 9],
        [3, 6, 7],
        [4, 1, 1]]])

In [53]:
#array[first_layer,complete_first_array,second_element_or_column]
x[1,:,1]

array([9, 2, 1])

In [54]:
#array[third_layer,second_row:last_row,second_column:last_column]
x[2,1:,1:]

array([[6, 7],
       [1, 1]])

In [55]:
#to display the second layer
#array[layer_index_number]
x[2]

array([[8, 4, 9],
       [3, 6, 7],
       [4, 1, 1]])

In [57]:
#creating a random 3x3 array
x=np.random.randint(10,size=(3,3))
x

array([[2, 7, 8],
       [7, 4, 9],
       [0, 9, 8]])

<span class="mark">x[ [ rowa , rowb ],[ cola , colb ] ]</span>  2 values

<span class="mark">x[ [rowa, rowb , rowc ],[cola , colb , colc ] ]</span>  3 values

used for indexing multiple values

In [58]:
x[[0,-1],[2,0]]

array([8, 0])

In [60]:
#or
x[[1,1,2],[0,1,2]]   #for indexing 3 values

array([7, 4, 8])

In [ ]:
x[[1,0],[0,2]]

array([2, 9])

In [ ]:
x[[0,0],[2,1]]  #first box column #second box row

array([9, 9])

### reversed indexing

#the first and the second rows got interchanged when reversed

In [13]:
import numpy as ne
x = ne.array([[91,2,3,],[2,3,4,]])
x

array([[91,  2,  3],
       [ 2,  3,  4]])

In [14]:
x[::-1]

array([[ 2,  3,  4],
       [91,  2,  3]])

### Boolean indexing

In [62]:
#created the array of (3,2,4)
import numpy as np

x= np.array([[[1,2,3,4],[5,6,7,8]],[[1,3,5,7],[2,4,6,8]],[[1,2,3,4],[4,5,6,7]]])
x

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 3, 5, 7],
        [2, 4, 6, 8]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [63]:
d=x>3 #passing the condition through the created array
d

array([[[False, False, False,  True],
        [ True,  True,  True,  True]],

       [[False, False,  True,  True],
        [False,  True,  True,  True]],

       [[False, False, False,  True],
        [ True,  True,  True,  True]]])

In [ ]:
'''If the condition satisfies then the out will be return true throgh the elements that satisfies
the condition'''

'If the condition satisfies then the out will be returen true throgh the elements that satisfies\nthe condition'

In [64]:
d= x==3 #will retuen true whereever in the array that satisfies the condition
d

array([[[False, False,  True, False],
        [False, False, False, False]],

       [[False,  True, False, False],
        [False, False, False, False]],

       [[False, False,  True, False],
        [False, False, False, False]]])

### Fancy indexing

<span class="mark">x[ [ rowa , rowb ],[ cola , colb ] ]</span>  2 values

<span class="mark">x[ [rowa, rowb , rowc ],[cola , colb , colc ] ]</span>  3 values

<span class="mark">x[ [ dima, dimb, dimc] , [ rowa, rowb , rowc ] , [cola , colb , colc ] ]</span> 3d

used for indexing multiple values

In [ ]:
# creating an array of 3x3

In [15]:
x = np.random.randint(10,high=50,size=(3,3))

In [16]:
x

array([[45, 41, 37],
       [24, 16, 25],
       [34, 22, 20]])

In [17]:
x[[1,2],[0,1]]             #firsr bracket==row second bracket==column

array([24, 22])

In [ ]:
#to find 3 different

In [ ]:
x[[1,0,2],[1,2,0]]

array([30, 11, 22])

In [ ]:
#creating a 2x3x3 array
x= np.array([[[1,2,3],[5,6,7],[1,2,3]],[[1,3,5],[2,4,6],[1,2,3]]])

In [ ]:
x

array([[[1, 2, 3],
        [5, 6, 7],
        [1, 2, 3]],

       [[1, 3, 5],
        [2, 4, 6],
        [1, 2, 3]]])

In [ ]:
# select 1,7,3,2,4,5,2,1

In [ ]:
x[[0,0,0,0,1,1,1,1],[0,1,2,2,1,0,2,2],[0,2,2,1,1,2,1,0]]

array([1, 7, 3, 2, 4, 5, 2, 1])

### sorting

In [ ]:
#to arrange in ascending order of row

In [ ]:
x = np.random.randint(10,high=50,size=10)

In [ ]:
x #before sorting

array([10, 14, 44, 35, 37, 12, 35, 13, 15, 23])

In [ ]:
x.sort()

In [ ]:
x  #after sorting

array([10, 12, 13, 14, 15, 23, 35, 35, 37, 44])

In [ ]:
#for the descending sort we have to reverse the sorted array

In [ ]:
x[::-1]    #sorted the array in desc oredr

array([44, 37, 35, 35, 23, 15, 14, 13, 12, 10])

In [ ]:
#creating a 2x3 array and sorting the same

In [18]:
x= np.array([[5,1,3],[2,1,4]])

In [19]:
x

array([[5, 1, 3],
       [2, 1, 4]])

In [20]:
x.sort()

In [21]:
x #sorting will take place in each rows

array([[1, 3, 5],
       [1, 2, 4]])

##### column sorting

<span class="burk">for sort column wise, axis = 0</span>

In [ ]:
x.sort(axis=0)    #colum sort orders the element in asc order of the column

In [ ]:
x

array([[2, 1, 3],
       [5, 1, 4]])

In [ ]:
x.sort(axis=1)  #row sorting =  x.sort() this is default

In [ ]:
x

array([[1, 3, 5],
       [1, 2, 4]])

In [ ]:
#sorting of a 3x4 array

In [ ]:
x= np.array([[5,1,3,4],[2,1,4,3],[7,3,8,6]])

In [ ]:
x

array([[5, 1, 3, 4],
       [2, 1, 4, 3],
       [7, 3, 8, 6]])

In [ ]:
x.sort(axis=1)

##### x  #row sorting

In [ ]:
#re running the array x created to default the sort

In [ ]:
x   #to save the chages we have to save it to a var

array([[5, 1, 3, 4],
       [2, 1, 4, 3],
       [7, 3, 8, 6]])

In [ ]:
x.sort(axis=0)

In [ ]:
x

array([[2, 1, 3, 3],
       [5, 1, 4, 4],
       [7, 3, 8, 6]])

In [ ]:
#creating a 3 dimensin array

In [22]:
x = np.array([[[20,5, 45, 40], [10, 4, 33, 30]],[[12, 5, 2, 13], [21, 19, 20, 7]]])

In [23]:
x

array([[[20,  5, 45, 40],
        [10,  4, 33, 30]],

       [[12,  5,  2, 13],
        [21, 19, 20,  7]]])

In [24]:
#row sorting

In [25]:
x.sort()

In [26]:
x

array([[[ 5, 20, 40, 45],
        [ 4, 10, 30, 33]],

       [[ 2,  5, 12, 13],
        [ 7, 19, 20, 21]]])

In [ ]:
#column sorting

In [ ]:
x

array([[[20,  5, 45, 40],
        [10,  4, 33, 30]],

       [[12,  5,  2, 13],
        [21, 19, 20,  7]]])

<span class="mark">in 3 dimension array axis=1 is column sort where as in 2d it is row sort remember</span>

In [ ]:
x.sort(axis=1)   

In [ ]:
x

array([[[10,  4, 33, 30],
        [20,  5, 45, 40]],

       [[12,  5,  2,  7],
        [21, 19, 20, 13]]])

##### dimension sort

In [ ]:
x

array([[[20,  5, 45, 40],
        [10,  4, 33, 30]],

       [[12,  5,  2, 13],
        [21, 19, 20,  7]]])

In [ ]:
''' in a 3 dimension array
The first row is above the third row
second row above the fourth row'''

In [ ]:
'''The dimension sort arranges the element in the first row and third row column vise
and similar goes to second and fourth'''

'The dimension sort arranges the element in the first row and third row column vise\nand similar goes to second and fourth'

In [ ]:
x.sort(axis=0)

In [ ]:
x

array([[[12,  5,  2, 13],
        [10,  4, 20,  7]],

       [[20,  5, 45, 40],
        [21, 19, 33, 30]]])

In [ ]:
#to find the reverse

In [ ]:
x[::-1]

array([[[20,  5, 45, 40],
        [21, 19, 33, 30]],

       [[12,  5,  2, 13],
        [10,  4, 20,  7]]])

In [ ]:
'''The reveseing of array in 3 dimension takes place by interchanging the position of layers'''

### Copy and view

In [ ]:
'''View imports a shotcut-like feature, while copy creates a duplicate'''

'View imports a shotcut-like feature, while copy creates a duplicate'

In [ ]:
'''any changes in the orginal file does not affect hthe duplicate
where as any changes in the original file affects the view file also'''

'any changes in the orginal file does not affect hthe duplicate\nwhere as any changes in the original file affects the view file also'

In [1]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
#view shallow copy #copy is deep copy

In [3]:
y=x.copy()
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
z=x.view()
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x[2]=5

In [6]:
x #second index position value replaced by 5

array([0, 1, 5, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#copy creates a duplicate file and view is the same file
print(x)
print(y)
print(z)

[0 1 5 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 5 3 4 5 6 7 8 9]


In [8]:
x = np.random.randint(10,size=(2,3))

In [9]:
x

array([[5, 8, 9],
       [2, 7, 2]])

In [10]:
y=x.copy()


In [11]:
y

array([[5, 8, 9],
       [2, 7, 2]])

In [12]:
c=x.view()

In [13]:
x[1,1]=8

In [14]:
x

array([[5, 8, 9],
       [2, 8, 2]])

In [16]:
print(x)
print(20*"*")
print(c)

[[5 8 9]
 [2 8 2]]
********************
[[5 8 9]
 [2 8 2]]


### reshape and flatten

####reshape to change the shape of the array 
:ex 2x3 to 3x2
in reshape we can the total number of elements in the array must be equal to the order of the array

 flatten to change any dimension array to one dimension array

In [17]:
x = np.arange(0,21)

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [19]:
b=x.reshape(7,3)

In [ ]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
c=x.reshape(3,7)

In [ ]:
c

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#create a 3x4 matrix  and convert it to 2x6

In [ ]:
x = np.arange(12).reshape(3,4)

In [ ]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = x.reshape(2,6)

In [ ]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
#create array between 1 to 10

In [ ]:
x = np.arange(1,11)

In [ ]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
c = x.reshape(2,5)

In [ ]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
b = c.flatten()   #to convert to one dimension

In [ ]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating a 4x5 array

In [ ]:
x = np.random.randint(10,size=(4,5))

In [ ]:
x

array([[5, 5, 5, 3, 7],
       [9, 8, 1, 9, 4],
       [3, 3, 8, 7, 0],
       [9, 4, 9, 1, 4]])

In [ ]:
b=x.reshape(2,5,2)
c = x.reshape(5,2,2)
d = x.reshape(2,2,5)

In [ ]:
print(b)

### resize

In reshape, we can only arrange arrays
in order of no. of elements
present, while in resize, the elements are repeated once the order above
the element size is exceeded.

In [ ]:
x = np.arange(10)

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b=np.resize(x,(3,7,3))    #resizing using np

In [ ]:
b

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [9, 0, 1],
        [2, 3, 4],
        [5, 6, 7],
        [8, 9, 0]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [9, 0, 1]],

       [[2, 3, 4],
        [5, 6, 7],
        [8, 9, 0],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0, 1, 2]]])

In [ ]:
c = x.resize()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#change 3x4 to 3x4x6

In [ ]:
x = np.random.randint(10,size=(3,4))

In [ ]:
y = np.resize(x,(3,4,6))

In [ ]:
y

array([[[0, 2, 5, 1, 6, 6],
        [1, 7, 3, 9, 9, 0],
        [0, 2, 5, 1, 6, 6],
        [1, 7, 3, 9, 9, 0]],

       [[0, 2, 5, 1, 6, 6],
        [1, 7, 3, 9, 9, 0],
        [0, 2, 5, 1, 6, 6],
        [1, 7, 3, 9, 9, 0]],

       [[0, 2, 5, 1, 6, 6],
        [1, 7, 3, 9, 9, 0],
        [0, 2, 5, 1, 6, 6],
        [1, 7, 3, 9, 9, 0]]])

### dot product 
same as matrix multiplication

In [ ]:
x=np.random.randint(10,size=(2,2))
y=np.random.randint(10,size=(2,2))

In [ ]:
x

array([[5, 6],
       [0, 6]])

In [ ]:
y

array([[5, 1],
       [7, 0]])

In [ ]:
np.dot(x,y)    #to find the dot product of two matrices, row of 1st matrix * column of 2nd matrix

array([[67,  5],
       [42,  0]])

In [ ]:
x = np.array([[2,3],[3,4]])
y = np.array([[1,5],[3,2]])

In [ ]:
x

array([[2, 3],
       [3, 4]])

In [ ]:
y

array([[1, 5],
       [3, 2]])

In [ ]:
np.dot(x,y)

array([[11, 16],
       [15, 23]])

In [ ]:
#creating a 3x3 matrix

In [ ]:
x = np.random.randint(10,size=(3,3))

In [ ]:
x

array([[1, 5, 3],
       [8, 9, 3],
       [6, 6, 6]])

##### min value in array
numpy.min(array)

In [ ]:
np.min(x)    # to find the minimum value in the array

1

##### minimum of values in every row
in 2dimension array 

axis = 1 is row-axis,

axis = 0 is column-axis

In [ ]:
np.min(x,axis=1)   #to find the minimum of every values in every row #row axis default in 2d

array([1, 3, 6])

##### maximum value in array
numpy.max(array_name)

In [ ]:
np.max(x)

9

In [ ]:
np.max(x,axis=1) #to find the max of every values in every row #axis=1 is row axis,defaut

array([5, 9, 6])

In [ ]:
#columnvise #axis=0

In [ ]:
np.max(x,axis=0)

array([8, 9, 6])

In [ ]:
#to find the the min or max of particular row of an array

'''numpy.max(array_name[index],axis=1)'''

'numpy.max(array_name[index],axis=1)'

In [ ]:
np.min(x[2])

6

In [ ]:
np.max(x[1])

9

In [ ]:
#to find the same for column we use axis = 0 
'''numpy.max(array_name[index],axis=0)'''

'numpy.max(array_name[index],axis=0)'

### mean,median

In [ ]:
#mean also known as average

In [ ]:
x = np.random.randint(10,size=(3,3))

In [ ]:
x

array([[4, 1, 0],
       [5, 9, 5],
       [4, 6, 4]])

In [ ]:
'''numpy.mean(array_name)'''

'numpy.mean(array_name)'

In [ ]:
np.mean(x)

4.222222222222222

In [ ]:
'''numpy.median(array_name)'''

In [ ]:
b = np.median(x)

In [ ]:
np.median(x)

4.0

In [ ]:
x

array([[0, 1, 4],
       [5, 5, 9],
       [4, 4, 6]])

In [ ]:
#to find mean and median axis wie

In [ ]:
np.median(x,axis=1) #for 2 dimension array axis=1==row

array([1., 5., 4.])

In [ ]:
np.median(x,axis=0)    #column wise median of 2 dimension array

array([4., 4., 6.])

In [ ]:
np.median(x[1])   #to find mean of perticular row of an array

5.0

In [ ]:
np.median(x[1],axis=0)  

5.0

In [ ]:
np.median(x[2],axis=0)   

4.0

In [ ]:
#creating a 3 dimension array

In [ ]:
x = np.random.randint(10,size=(2,3,3))

In [ ]:
x

array([[[7, 9, 5],
        [1, 2, 4],
        [9, 3, 2]],

       [[0, 6, 3],
        [6, 7, 3],
        [0, 8, 5]]])

In [ ]:
np.mean(x)

4.444444444444445

In [ ]:
np.median(x)

4.5

##### In a 3 dimension array,the zeroth axis is layer axis
column =1
row=2 default

In [ ]:
np.median(x,axis=0)    #layer wise

array([[3.5, 7.5, 4. ],
       [3.5, 4.5, 3.5],
       [4.5, 5.5, 3.5]])

In [ ]:
'''when axis = o  the nedian will compare the elementd one above another in the layer and return the 2 dimension median array'''

'when axis = o  the nedian will compare the elementd one above another in the layer and return the 2 dimension median array'

In [ ]:
np.min(x,axis=0)   #axis = 0  min of layer1 and corresponding element in layer 2

array([[0, 6, 3],
       [1, 2, 3],
       [0, 3, 2]])

In [ ]:
np.max(x,axis=0) 

array([[7, 9, 5],
       [6, 7, 4],
       [9, 8, 5]])

In [ ]:
#axis = 1 column wise

In [ ]:
np.min(x,axis=1) 

array([[1, 2, 2],
       [0, 6, 3]])

In [ ]:
np.max(x,axis=1) 

array([[9, 9, 5],
       [6, 8, 5]])

In [ ]:
#row wise axis=2

In [ ]:
np.min(x,axis=2) 

array([[5, 1, 2],
       [0, 3, 0]])

In [ ]:
np.max(x,axis=2) 

array([[9, 4, 9],
       [6, 7, 8]])

In [ ]:
#first layer 1 st row ewan and media

In [ ]:
np.median(x[0,0])

7.0

In [ ]:
np.mean(x[1,0]) 

3.0

In [ ]:
np.median(x[1,0])

3.0

In [ ]:
#do the same with column axis

### vstack,hstack

both functions similarly, they join the two arrays one above another in a row wise manner

In [ ]:
#create 2 2x2 array

In [ ]:
#vstack and row stack are same

In [74]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [75]:
y = np.arange(4).reshape(2,2)
y

array([[0, 1],
       [2, 3]])

In [76]:
c = np.vstack((x,y))
c

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [77]:
#row stacks
d = np.row_stack((x,y))
d

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

##### hstack,column_stack
Similar to each other, both functions join the two arrays column by
column

In [ ]:
e = np.hstack((x,y))  #horizontal stacking

In [ ]:
e

array([[0, 1, 0, 1],
       [2, 3, 2, 3]])

In [ ]:
f = np.column_stack((x,y))  #horizontal and column stack are same

In [ ]:
#create a 3x3 matrix and apply vstack,hstact,roestack,colstack

In [ ]:
x = np.random.randint(10,size=(3,3))

In [ ]:
y = np.random.randint(10,size=(3,3))

In [ ]:
x

array([[2, 9, 0],
       [0, 1, 6],
       [0, 6, 9]])

In [ ]:
y

array([[9, 2, 6],
       [2, 8, 6],
       [3, 0, 7]])

In [ ]:
c = np.vstack((x,y))

In [ ]:
d = np.row_stack((x,y))

In [ ]:
e = np.hstack((x,y))

In [ ]:
f = np.column_stack((x,y))

In [ ]:
c

array([[2, 9, 0],
       [0, 1, 6],
       [0, 6, 9],
       [9, 2, 6],
       [2, 8, 6],
       [3, 0, 7]])

In [ ]:
d

array([[2, 9, 0],
       [0, 1, 6],
       [0, 6, 9],
       [9, 2, 6],
       [2, 8, 6],
       [3, 0, 7]])

In [ ]:
f

array([[2, 9, 0, 9, 2, 6],
       [0, 1, 6, 2, 8, 6],
       [0, 6, 9, 3, 0, 7]])